version: "3"
services:
  shell:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - IMAGE=docker.io/nvidia/cuda
        - TAG=11.5.1-cudnn8-runtime-ubuntu20.04
        - USER=developer
    user: developer
    entrypoint: sleep infinity
    working_dir: /workspace
    volumes:
      - ..:/workspace
    ports:
      - 8888:8888
